# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  quanlysinhvienapi:
    image: quanlysinhvienapi
    build:
      context: .
      dockerfile: QuanLySinhVien-main/QuanLySinhVienApi/Dockerfile
    ports:
      - 5146:5146
