# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  quanlysinhvienapi:
    image: quanlysinhvienapi
    build:
      context: .
      dockerfile: QuanLySinhVien-main/QuanLySinhVienApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5146:5146
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
